### ISSUE TITLE
running slow.

### ISSUE THREAD

**Issue by vegaquark** [UberGallery/UberGallery#12]
May there be a problem with cached thumbnails? I don't know
But the page is loading really slow...  can i force not to check for new pictures, or creating thumbs? just show them?
Php works hard for about 30-40 seconds and then the page shows up...

**Comment by moshekaplan** [comment]
What I did was enable pagination, visit each page, and then disable pagination.
That allowed the script to generate the thumbnails in chunks and prevent the timing-out from the thumbnail generation.
