### ISSUE TITLE
Warning for invalid JPEG files

### ISSUE THREAD

**Issue by chancrescolex** [UberGallery/UberGallery#22]
Love your plugin, but I have encountered a problem that seems to be pretty common after I searched on google for a bit. I am getting a lot of PHP warnings for invalid jpeg files. The images are automatically uploaded from a security camera. Is there any way to just hide the invalid ones and get rid of the PHP warning?

This is what shows up above my gallery (with some personal info deleted)

Warning: imagecreatefromjpeg() [function.imagecreatefromjpeg]: gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: 1 extraneous bytes before marker 0xd9 in ---------------------------------/resources/UberGallery.php on line 678

Warning: imagecreatefromjpeg() [function.imagecreatefromjpeg]: '---------------------------------/gallery-images/78A5DD06E9E6(wansview)_1_20130110095430_34.jpg' is not a valid JPEG file in /---------------------------------/resources/UberGallery.php on line 678

Warning: imagecopyresampled(): supplied argument is not a valid Image resource in /---------------------------------/resources/UberGallery.php on line 679

Warning: imagecreatefromjpeg() [function.imagecreatefromjpeg]: gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: 1 extraneous bytes before marker 0xd9 in /---------------------------------/resources/UberGallery.php on line 678

Warning: imagecreatefromjpeg() [function.imagecreatefromjpeg]: '/---------------------------------/gallery-images/78A5DD06E9E6(wansview)_1_20130110095535_39.jpg' is not a valid JPEG file in /---------------------------------/resources/UberGallery.php on line 678

Warning: imagecopyresampled(): supplied argument is not a valid Image resource in /---------------------------------/resources/UberGallery.php on line 679

My quick fix - Added @ before imagecreatefromjpeg and imagecopyresampled

**Comment by webknowledgefree** [comment]
I have also problem of that kind, so i have used the following syntax and that work for me
 $size=getimagesize($target_file);
 					 if(!$size)
					 {
						   $msg="Missing or incorrect image file."; 
					 }
					 else if($size[2]!=2)
					 {
						  $msg="Invalid image file.";
					 }

**Comment by sagarsdeshmukh** [comment]
I also face same issue.

we used below code to fix this issue and it works for me,

...
$image = @ImageCreateFromJpeg($image_name);
if (!$image)
{
$image= imagecreatefromstring(file_get_contents($image_name));
}
...
Hope this helps you...:)

**Comment by BilalBhatti** [comment]
Add below on the top of UberGallery.php

`ini_set("gd.jpeg_ignore_warning", 1);`
