### ISSUE TITLE
(Re)generate cache based on filemtime

### ISSUE THREAD

**Issue by jfache** [UberGallery/UberGallery#30]
Hi there,

I have been using your script for a short time, but I wonder why you chose to (re)generate the thumbnail every N minutes.

Right now, the script might regenerate thumbnails even if the source image hasn't changed.

Comparing the filemtime of the source image and its thumbnail might allow for image specific thumbnail regeneration.

What do you think?

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X (currently master) branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).
