### ISSUE TITLE
The HTML template in `createGallery` function should not use `id` for styling.

### ISSUE THREAD

**Issue by mytharcher** [UberGallery/UberGallery#35]
Especially in multi-galleries, the ids of HTML container elements become duplicated.

I suggest change `id` to `class` instead.

Additionally, the best way for create view HTML is to use a template engine like [mustache](https://github.com/bobthecow/mustache.php) or other. So that the controller and view can be seperated and view could be easy to modify by users.

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X (currently master) branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).
