### ISSUE TITLE
Make gallery title configurable

### ISSUE THREAD

**Issue by hschletz** [UberGallery/UberGallery#36]
The gallery title in the heading and in the &lt;title&gt; element is hardcoded to "UberGallery", which is just confusing to the visitor. It should be configurable via the INI file.

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X (currently master) branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).
