### ISSUE TITLE
Transparent PNGs have black background

### ISSUE THREAD

**Issue by PHLAK** [UberGallery/UberGallery#42]
Source: https://groups.google.com/forum/#!topic/ubergallery/pqeEVKIly-k

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X (currently master) branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).

**Comment by saol89** [comment]
## for transparent backround in png image

in the fille /resources/UberGallery.php around line 696
_overwrite this:_
       ` $newImage = imagecreatetruecolor($thumbWidth, $thumbHeight);`

_with this:_

```
 $newImage = imagecreatetruecolor($thumbWidth, $thumbHeight);
   		imagealphablending($newImage, false);
        imagesavealpha($newImage, true);
```


@PHLAK
