### ISSUE TITLE
createGallery() should return XHTML

### ISSUE THREAD

**Issue by synox** [UberGallery/UberGallery#45]
The method ``createGallery($directory, $relText)`` should return XHML text instead of printing it, as noted the method comment. 

https://github.com/UberGallery/UberGallery/blob/master/resources/UberGallery.php#L152

If you want to print it, I suggest creating another void-function with "print" in the name. 

Motivation: When it returns instead of printing, it is easier to integrate into another application.

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X (currently master) branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).
