### ISSUE TITLE
Deactivate the Thumnail feature

### ISSUE THREAD

**Issue by fxworks2013** [UberGallery/UberGallery#51]
Hi, 

I have placed your great scripts on my server. Everything works so far good.
I just want to disable the thumbnail generation/create-process and just show the images located in the gallery-images directory, because I already have pre-formatted small images there.

How can this be done?

Great work! Keep going.

Cheers
fxworker

**Comment by PHLAK** [comment]
There is no way to disable the generation of thumbnails.  This is the entire point of UberGallery.
