### ISSUE TITLE
Show previous photo on click in the left half

### ISSUE THREAD

**Issue by peraburek** [UberGallery/UberGallery#52]
I would like to be able to go to previous image based on click of left part of the image

http://stackoverflow.com/questions/30236867/show-previous-photo-on-click-in-the-left-half-of-the-current-photo-in-colorbox

I believe it should be added to /resources/templates/colorboxScripts.php
but I am not sure where

$("#cboxLoadedContent").click(function (e) {
    var pWidth = $(this).innerWidth();
    var pOffset = $(this).offset();
    var x = e.pageX - pOffset.left;
    if (pWidth / 2 > x)
        $.colorbox.prev();
    else
        $.colorbox.next();
});

please advise

**Comment by PHLAK** [comment]
Try adding it at the bottom of the page just BEFORE the closing `</script>` tag.

**Comment by peraburek** [comment]
it doesn't work, I have tried it

could you please add this code on one of your demo UberGallery, so you can see where is the problem, I am not skilled with javascript
