### ISSUE TITLE
Image iterator doesn't recurse into subdirectories

### ISSUE THREAD

**Issue by h0dgep0dge** [UberGallery/UberGallery#56]
I noticed that the gallery will only show images that are the immediate children of the `gallery-images` directory. If I get around to it I may implement this myself and submit a pull request, but if someone can implement it easily in the meantime, go ahead.

**Comment by PHLAK** [comment]
I am closing this issue as I've started work on UberGallery 3.0 and wont be accepting any more issues for new features (only bug and security fixes) against the 2.X branch.  UberGallery 3.0 is a complete rewrite but will take all current issues and PRs into consideration during development.  If you'd like to comment or contribute to the development of version 3.0 please do so in our [UberGallery 3.0 Roadmap issue](https://github.com/UberGallery/UberGallery/issues/58).
