### ISSUE TITLE
You should consider making it a video / picture gallery...

### ISSUE THREAD

**Issue by dkromp** [UberGallery/UberGallery#62]

**Comment by PHLAK** [comment]
I've considered support for videos but that adds a whole extra layer of complexity that I feel is unnecessary.  I'd rather focus on making UberGallery a great photo gallery and let someone else handle videos.

**Comment by dkromp** [comment]
Can you suggest an alternative to UberGallery that is just as simple but
handles videos too?

On Mon, Sep 19, 2016 at 11:49 AM, Chris Kankiewicz <notifications@github.com
