### ISSUE TITLE
The folders including  "resources/themes/uber-blue"  is empty.

### ISSUE THREAD

**Issue by Amamatthew** [UberGallery/UberGallery#63]
The themes folders including  `"resources/themes/uber-blue"` and so on is empty.
When I download the UberGallery from github, upload and open `index.php`  file in my web server, I see  `ERROR: Failed to initialize theme`

Ok, I see the themes in the same Github warehouse --  https://github.com/UberGallery

**Comment by PHLAK** [comment]
You can find full downloads at http://www.ubergallery.net/#download
