### ISSUE TITLE
Changing the Image Directory of UberGallery

### ISSUE THREAD

**Issue by BilalBhatti** [UberGallery/UberGallery#65]
Hello,

I want to set the image directory from "gallery-images" to the root where index.php is placed.

Changing

$galleryArray = $gallery->readImageDirectory('gallery-images');

to

$galleryArray = $gallery->readImageDirectory('/');

didn't work.

**Comment by PHLAK** [comment]
Try `$galleryArray = $gallery->readImageDirectory('.');`
