### ISSUE TITLE
image popups not opening on https

### ISSUE THREAD

**Issue by iris3th** [UberGallery/UberGallery#69]
hi, I'm trying to use UberGallery on lighttpd / https and when clicking on any thumbnails, it doesn't open the full image in a popup window, opens the image in the actual browser tab instead. Trying to figure out what the problem is, any help appreciated.

**Comment by DivadYegdihc** [comment]
Similarly so - this has just presented itself as an issue with a couple of sites where I am using this.

**Comment by PHLAK** [comment]
Check your browser's web console for an error like the following:

![screenshot 2018-07-03 08 53 16](https://user-images.githubusercontent.com/53531/42230811-c7951f5e-7e9e-11e8-8506-e6a154a9969a.png)
